### ISSUE TITLE
3 Glitches 

### ISSUE THREAD

**Issue by ForgeGMP** [GTACOOP-R/GTACoop-R#13] opened 2021-07-25 01:27 UTC
1:Cuando disparas al otro jugador, el otro jugador recibe el daño muy pocas veces,casi ninguna

2:The cars when the other player has them modified or something like that, the other player sees them as if they were normal, and even sometimes the car is another color, or it is duplicated

3:When you get on as a passenger in the other's car, he stays still, sometimes he moves like crazy being glitched

Thanks for paying attention to me, and thank you very much if you correct it, a thanks to the creators for the mod

**Comment by oldnapalm** [comment] 2021-08-02 14:23
"1" seems to be caused by `SET_CAN_ATTACK_FRIENDLY`, if both 2nd and 3rd argument are true, you can't shoot other players, need to use false for the 3rd one.

`Function.Call(Hash.SET_CAN_ATTACK_FRIENDLY, Game.Player.Character, true, false);`

http://www.dev-c.com/nativedb/func/info/b3b1cb349ff9c75d

Also, `SET_PED_CAN_BE_TARGETTED` takes the ped handle as first argument, we could use `Game.Player.Character.CanBeTargetted = true` but it doesn't seem to make difference.

https://github.com/crosire/scripthookvdotnet/blob/main/source/scripting_v3/GTA/Entities/Peds/Ped.cs#L746

**Comment by oldnapalm** [comment] 2021-08-06 15:59
After the latest update (https://github.com/GTACOOP-R/GTACoop-R/commit/b3edbd9ed552a7b076ff009a4644ca040d4b9549#diff-27565fe08392310ee8ac500bdcb77238f70107b5621186bb29291fe929a949cfR25) I can shoot other players, but no visible damage and the other players can't see me aiming or shooting.

**Comment by EntenKoeniq** [comment] 2021-08-17 17:05
1: Will be fixed with the next updates
2: Vehicle colors have been synchronized since version 0.5.0
3: Fixed

**Closed by EntenKoeniq** 2021-08-17 17:05 UTC
Labels: bug
